spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_aspect_demo
spring.datasource.username=postgres
spring.datasource.password=dbos
spring.datasource.driver-class-name=org.postgresql.Driver